name: CreaciÃ³n de Cliente

on:
  workflow_dispatch:  # Permite ejecutarlo manualmente

jobs:
  notificar_creacion:
    runs-on: ubuntu-latest
    steps:
      - name: NotificaciÃ³n de nuevo cliente
        run: echo "ğŸ†• Se ha creado un nuevo cliente en la aplicaciÃ³n. Todos los miembros han sido notificados."
