<<<<<<< HEAD
name: Consultar Cliente
=======
name: Consulta de Cliente
>>>>>>> 5715c315de3ac7115aa102488f4cd9e2b7b15b58

on:
  workflow_dispatch:

jobs:
<<<<<<< HEAD
  consultar_cliente:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Simular consulta de cliente
      run: |
        echo "ðŸ”µ InformaciÃ³n de cliente consultada."
        echo "ðŸ“£ NotificaciÃ³n a todos los miembros del equipo."

=======
  notificar_consulta:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensaje de consulta
        run: echo "ðŸ” Se ha consultado la informaciÃ³n de un cliente."
>>>>>>> 5715c315de3ac7115aa102488f4cd9e2b7b15b58
