<<<<<<< HEAD

name: Crear Nuevo Cliente

on:
  workflow_dispatch:  # Permite ejecutar manualmente desde GitHub

jobs:
  crear_cliente:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Simular creaci贸n de cliente
      run: |
        echo " Nuevo cliente creado en el sistema Axanet."
        echo " Notificaci贸n a todos los miembros del equipo."
=======
name: Creaci贸n de Cliente

on:
  workflow_dispatch:

jobs:
  notificar_creacion:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensaje de creaci贸n
        run: echo " Se ha creado un nuevo cliente en la aplicaci贸n."
>>>>>>> 5715c315de3ac7115aa102488f4cd9e2b7b15b58
